services:
  postgres:
    image: postgres:17
    container_name: industrial-postgres
    environment:
      POSTGRES_DB: industrial_monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: