import { useEffect, useState } from "react";
import axios from "axios";
import StatsCard from "./components/StatsCard";
import ReadingsChart from "./components/ReadingsChart";
import MachinesTable from "./components/MachinesTable";
import AlertsPanel from "./components/AlertsPanel";
import CreateMachineForm from "./components/CreateMachineForm";
import CreateSensorForm from "./components/CreateSensorForm";
import SensorsTable from "./components/SensorsTable";
import ReadingsTable from "./components/ReadingsTable";
import "./App.css";

const API_URL = "http://localhost:8080/api";

function App() {
  const [activePage, setActivePage] = useState("overview");
  const [stats, setStats] = useState(null);
  const [machines, setMachines] = useState([]);
  const [readings, setReadings] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [sensors, setSensors] = useState([]);
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 5000);
    return () => clearInterval(interval);
  }, []);

  async function fetchData() {
    const [statsRes, machinesRes, readingsRes, alertsRes, sensorsRes] =
      await Promise.all([
        axios.get(`${API_URL}/dashboard`),
        axios.get(`${API_URL}/machines`),
        axios.get(`${API_URL}/readings`),
        axios.get(`${API_URL}/alerts`),
        axios.get(`${API_URL}/sensors`),
      ]);

    setStats(statsRes.data);
    setMachines(machinesRes.data);
    setReadings(readingsRes.data);
    setAlerts(alertsRes.data);
    setSensors(sensorsRes.data);
    setLastUpdated(new Date().toLocaleTimeString());
  }

  function renderPage() {
    if (!stats) {
      return <div className="loading-card">Loading dashboard data...</div>;
    }

    if (activePage === "overview") {
      return (
        <>
          <section className="stats-grid">
            <StatsCard label="Machines" value={stats.totalMachines} helper="registered assets" />
            <StatsCard label="Active Sensors" value={stats.activeSensors} helper="currently reporting" />
            <StatsCard label="Readings" value={stats.totalReadings} helper="stored measurements" />
            <StatsCard label="Offline" value={stats.offlineMachines} helper="requires attention" danger />
          </section>

          <section className="dashboard-grid">
            <ReadingsChart readings={readings} />

            <div className="right-column">
              <AlertsPanel alerts={alerts.slice(0, 5)} />

              <section className="insight-card">
                <h2>System Health</h2>

                <div className="health-row">
                  <span>Operational status</span>
                  <strong className="success">Stable</strong>
                </div>

                <div className="health-row">
                  <span>Data refresh</span>
                  <strong>5s interval</strong>
                </div>

                <div className="health-row">
                  <span>Offline machines</span>
                  <strong className={stats.offlineMachines > 0 ? "danger-text" : "success"}>
                    {stats.offlineMachines}
                  </strong>
                </div>

                <p className="insight-note">
                  Sensor readings are automatically generated by the backend simulator and persisted in PostgreSQL.
                </p>
              </section>
            </div>
          </section>
        </>
      );
    }

    if (activePage === "machines") {
      return (
        <>
          <CreateMachineForm onMachineCreated={fetchData} />
          <MachinesTable machines={machines} />
        </>
      );
    }

    if (activePage === "sensors") {
      return (
        <>
          <CreateSensorForm machines={machines} onSensorCreated={fetchData} />
          <SensorsTable sensors={sensors} />
        </>
      );
    }

   if (activePage === "readings") {
      return (
        <>
          <ReadingsChart readings={readings} />
          <ReadingsTable readings={readings} />
        </>
      );
    }
    if (activePage === "alerts") {
      return <AlertsPanel alerts={alerts} />;
    }
  }

  const pageTitles = {
    overview: "Operations Dashboard",
    machines: "Machine Management",
    sensors: "Sensor Management",
    readings: "Sensor Readings",
    alerts: "Active Alerts",
  };

  const pageSubtitles = {
    overview: "Monitor machine health, sensor activity and live industrial readings.",
    machines: "Create, view and manage industrial machines.",
    sensors: "Register and monitor sensors linked to machines.",
    readings: "Visualize telemetry generated by the sensor simulator.",
    alerts: "Review warnings generated by threshold-based monitoring.",
  };

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-icon">IM</div>
          <div>
            <strong>Industrial</strong>
            <span>Monitoring</span>
          </div>
        </div>

        <nav>
          {["overview", "machines", "sensors", "readings", "alerts"].map((page) => (
            <button
              key={page}
              className={activePage === page ? "active" : ""}
              onClick={() => setActivePage(page)}
            >
              {page.charAt(0).toUpperCase() + page.slice(1)}
            </button>
          ))}
        </nav>
      </aside>

      <main className="main-content">
        <header className="page-header">
          <div>
            <p className="eyebrow">Real-time factory telemetry</p>
            <h1>{pageTitles[activePage]}</h1>
            <p className="subtitle">{pageSubtitles[activePage]}</p>
          </div>

          <div className="header-status">
            <span className="pulse"></span>
            <div>
              <strong>Live system</strong>
              <small>Updated {lastUpdated || "loading..."}</small>
            </div>
          </div>
        </header>

        {renderPage()}
      </main>
    </div>
  );
}

export default App;