import { useEffect, useState } from "react";
import axios from "axios";
import StatsCard from "./components/StatsCard";
import ReadingsChart from "./components/ReadingsChart";
import MachinesTable from "./components/MachinesTable";
import AlertsPanel from "./components/AlertsPanel";
import CreateMachineForm from "./components/CreateMachineForm";
import "./App.css";

const API_URL = "http://localhost:8080/api";

function App() {
  const [stats, setStats] = useState(null);
  const [machines, setMachines] = useState([]);
  const [readings, setReadings] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    fetchData();

    const interval = setInterval(fetchData, 5000);

    return () => clearInterval(interval);
  }, []);

  async function fetchData() {
    const [statsRes, machinesRes, readingsRes, alertsRes] = await Promise.all([
      axios.get(`${API_URL}/dashboard`),
      axios.get(`${API_URL}/machines`),
      axios.get(`${API_URL}/readings`),
      axios.get(`${API_URL}/alerts`),
    ]);

    setStats(statsRes.data);
    setMachines(machinesRes.data);
    setReadings(readingsRes.data);
    setAlerts(alertsRes.data);
    setLastUpdated(new Date().toLocaleTimeString());
  }

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-icon">IM</div>

          <div>
            <strong>Industrial</strong>
            <span>Monitoring</span>
          </div>
        </div>

        <nav>
          <a className="active">Overview</a>
          <a>Machines</a>
          <a>Sensors</a>
          <a>Readings</a>
          <a>Alerts</a>
        </nav>
      </aside>

      <main className="main-content">
        <header className="page-header">
          <div>
            <p className="eyebrow">Real-time factory telemetry</p>
            <h1>Operations Dashboard</h1>
            <p className="subtitle">
              Monitor machine health, sensor activity and live industrial
              readings.
            </p>
          </div>

          <div className="header-status">
            <span className="pulse"></span>

            <div>
              <strong>Live system</strong>
              <small>Updated {lastUpdated || "loading..."}</small>
            </div>
          </div>
        </header>

        {!stats ? (
          <div className="loading-card">Loading dashboard data...</div>
        ) : (
          <>
            <section className="stats-grid">
              <StatsCard
                label="Machines"
                value={stats.totalMachines}
                helper="registered assets"
              />

              <StatsCard
                label="Active Sensors"
                value={stats.activeSensors}
                helper="currently reporting"
              />

              <StatsCard
                label="Readings"
                value={stats.totalReadings}
                helper="stored measurements"
              />

              <StatsCard
                label="Offline"
                value={stats.offlineMachines}
                helper="requires attention"
                danger
              />
            </section>

            <section className="dashboard-grid">
              <ReadingsChart readings={readings} />

              <div className="right-column">
                <AlertsPanel alerts={alerts} />

                <section className="insight-card">
                  <h2>System Health</h2>

                  <div className="health-row">
                    <span>Operational status</span>
                    <strong className="success">Stable</strong>
                  </div>

                  <div className="health-row">
                    <span>Data refresh</span>
                    <strong>5s interval</strong>
                  </div>

                  <div className="health-row">
                    <span>Offline machines</span>
                    <strong
                      className={
                        stats.offlineMachines > 0 ? "danger-text" : "success"
                      }
                    >
                      {stats.offlineMachines}
                    </strong>
                  </div>

                  <p className="insight-note">
                    Sensor readings are automatically generated by the backend
                    simulator and persisted in PostgreSQL.
                  </p>
                </section>
              </div>
            </section>
            <CreateMachineForm onMachineCreated={fetchData} />

            <MachinesTable machines={machines} />
          </>
        )}
      </main>
    </div>
  );
}

export default App;